# Generated by Django 4.2.4 on 2024-03-01 15:26

import MyPlant_App.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[MyPlant_App.profiles.validators.validate_name_capital_letter])),
                ('last_name', models.CharField(max_length=20, validators=[MyPlant_App.profiles.validators.validate_name_capital_letter])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
